version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@3.0.0
  snyk: snyk/snyk@2.3.0

jobs:
  # Job separado para tests - principio de responsabilidad única
  test:
    docker:
      - image: cimg/php:8.1
    working_directory: ~/cicd-ia
    resource_class: small
    steps:
      - checkout

      - run:
          name: Instalar dependencias PHP
          command: |
            composer install
      - run:
          name: ejecutar tests con coverage usando PHPDBG
          command: |
            phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
          environment:
              XDEBUG_MODE: coverage
      - run:
          name: Verificar coverage generado
          command: |
            if [ -f coverage.xml ]; then
              echo "✅ coverage.xml generado correctamente"
            else
              echo "❌ coverage.xml no encontrado"
            fi
      # Guardar resultados para el job code_quality
      - persist_to_workspace:
          root: .
          paths:
            - coverage.xml
      
  # Job separado para análisis de código
  code_quality:
    docker:
      - image: cimg/php:8.1
    resource_class: small
    steps:
      - checkout

      - run:
          name: Instalar dependencias PHP
          command: composer install

  # Recuperar coverage.xml del job anterior 
      - attach_workspace:
          at: .
      - run:
          name: Verificar coverage generado
          command: |
            if [ -f coverage.xml ]; then
              echo "✅ coverage.xml encontrado"
            else
              echo "❌ coverage.xml no encontrado"
            fi

      - run:
          name: Análisis estático con PHPStan
          command: |
            vendor/bin/phpstan analyse src/ \
              --error-format=checkstyle \
              --no-progress \
              > phpstan-report.xml || true
      
      - run:
          name: Análisis de code mess con PHPMD
          command: |
            vendor/bin/phpmd src/ xml \
              cleancode,codesize,controversial,design,naming,unusedcode \
              > phpmd-report.xml || true
      
      # Análisis con SonarCloud
      - sonarcloud/scan:
          cache_version: 2
      
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          additional-arguments: "--file=composer.json --json-file-output=snyk-report.json"

  # Job para validar que el proyecto se puede buildear
  build_validation:
    docker:
      - image: cimg/php:8.1
    resource_class: small
    steps:
      - checkout
      
      - run:
          name: Instalar dependencias PHP
          command: |
            composer install

      - run:
          name: Validar sintaxis PHP
          command: find src/ -name "*.php" -exec php -l {} \;
      
      - run:
          name: Validar composer.json
          command: composer validate --strict
      
      - run:
          name: Verificar autoloader
          command: composer dump-autoload --optimize --strict-psr

  docker_build_and_push:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: Build Docker image
          command: |
            docker build -t jeffnacato/cicd-ia:$CIRCLE_SHA1 .
            docker tag jeffnacato/cicd-ia:$CIRCLE_SHA1 jeffnacato/cicd-ia:latest
      
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push jeffnacato/cicd-ia:$CIRCLE_SHA1
            docker push jeffnacato/cicd-ia:latest

workflows:
  development_pipeline:
    jobs:
      - build_validation:
          filters:
            branches:
              only:
                - develop
                - /feature\/.*/
      - test:
          filters:
            branches:
              only:
                - develop
                - /feature\/.*/
      - code_quality:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - /feature\/.*/
  
  main_branch:
    jobs:
      - build_validation:
          filters:
            branches:
              only:
                - main
      - test:
          filters:
            branches:
              only:
                - main
      - code_quality:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - docker_build_and_push:
          requires:
            - test
            - code_quality
          filters:
            branches:
              only:
                - main

  release_pipeline:
    jobs:
      - build_validation:
          filters:
            branches:
              only:
                - /release\/.*/
      - test:
          filters:
            branches:
              only:
                - /release\/.*/
      - code_quality:
          requires:
            - test
          filters:
            branches:
              only:
                - /release\/.*/
  
  hotfix_pipeline:
    jobs:
      - build_validation:
          filters:
            branches:
              only:
                - /hotfix\/.*/
      - test:
          filters:
            branches:
              only:
                - /hotfix\/.*/
      - code_quality:
          requires:
            - test
          filters:
            branches:
              only:
                - /hotfix\/.*/