version: 2.1

jobs:
  code-quality:
    docker:
      - image: cimg/php:8.2
    resource_class: small
    steps:
      - checkout
      - run: vendor/bin/phpunit --log-junit /home/circleci/project/test-results/phpunit.xml
      - run: vendor/bin/phpstan analyse src/ --error-format=junit > /home/circleci/project/test-results/phpstan.xml || true
      - run: vendor/bin/phpmd src/ xml cleancode,codesize,controversial,design,naming,unusedcode > /home/circleci/project/test-results/phpmd.xml || true
      - store_test_results:
          path: /home/circleci/project/test-results/

workflows:
  test:
    jobs:
      - code-quality